_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 40
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 40
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.18.7
            "8":
                - 1
                - 6
            "12": 0.18.7
            "13": linux-x86_64
DSBN:
    value: false
MVC:
    value: false
amp:
    value: true
batch_size:
    value: 32
dab_weight:
    value: 0
dataset_name:
    value: covid
do_train:
    value: true
dropout:
    value: 0.2
ecs_thres:
    value: 0
epochs:
    value: 10
fast_transformer:
    value: true
freeze:
    value: false
include_zero_gene:
    value: false
layer_size:
    value: 128
load_model:
    value: /tscc/nfs/home/s5srinivasan/scgpt-project/covid-annotation-scgpt/save/scGPT-human
lr:
    value: 0.0001
mask_ratio:
    value: 0
n_bins:
    value: 51
nhead:
    value: 4
nlayers:
    value: 4
pre_norm:
    value: false
save_eval_interval:
    value: 5
schedule_ratio:
    value: 0.9
seed:
    value: 0
